title: <img src="./logo.svg" alt="LoAT">
email: florian.frohn@cs.rwth-aachen.de
description: >- # this means to ignore newlines until "baseurl:"
  We present a variant of the ADCL calculus that can prove non-termination
  of transition systems. An empirical evaluation of our implementation in
  our tool LoAT shows that it outperforms other state-of-the-art tools.
github_username:  ffrohn
theme: jekyll-theme-cayman
github:
  is_project_page: false